config/routes.rb
Timetracking::Application.routes.draw do
  get '/' => 'site#home'

  resources :projects do 
    resources :entries
  end 

end

app/models/entry.rb
class Entry < ActiveRecord::Base
	belongs_to :project

	validates :hours, numericality: true
	validates :date, presence: true
	validates :hours, presence: true
	validates :minutes, presence: true, numericality: true
	validates_associated :project
	
end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :entries
	
	validates :name, uniqueness: true
	validates :name, presence: true
	validates :name, length: {maximum: 30}
	validates :name, format: {with: /\w/}

	def self.iron_find(id)
		where(id: id).first
	end 
	def self.clean_old
		Project.where("created_at < ?", 1.week.ago).destroy_all
	end 
	def self.last_created_projects(n)
		Project.order("created_at DESC").limit(n)
	end 
	def entries_for(date)
		entries.where(date: date.beginning_of_month..date.end_of_month)
	end
	def total_hours_in_month(month, year)
		date = DateTime.new(year, month)
		es = entries_for(date)
		hours = 0;
		minutes = 0;
		es.each do |entry| 
			hours += entry.hours
			minutes +=entry.minutes
		end
		(minutes/60) + hours 
	end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
	def index
		@project = Project.find params[:project_id]
		@date = DateTime.now
		@entries = @project.entries_for(@date)
		p @entries
	end
	def new
		@project = Project.find params[:project_id]
		@entry = @project.entries.new
	end
	def create
		@project = Project.find params[:project_id]
		@entry = @project.entries.new(entry_params())
		#@entry.user = User.find(session[:user_id])

		if @entry.save
			flash[:notice] = "Entry created successfully!"
			UserMailer.entry_created(@project).deliver
			#entry_created is a class method. 
			redirect_to project_entries_path(@project) 
			#action: 'index', controller: 'entries', project_id: @project.id
		else 
			flash.now[:error] = "Entry hasn't been created."
			render 'new'
		end
	end 

	def edit
		@project = Project.find params[:project_id]
		@entry = @project.entries.find params[:id]
	end 

	def update
		@entry = Entry.find(params[:id])
		if @entry.update_attributes entry_params
			redirect_to project_entries_path
		else
			@errors = @entry.errors.full_messages
			render 'edit'
		end
	end

	def destroy
		@project = Project.find params[:project_id]
		@entry = @project.entries.find params[:id]
		@entry.delete
		redirect_to project_entries_path
	end

	private 
	def entry_params
		params.require(:entry).permit(:hours, :minutes, :date, :comments)
	end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def index
		#@projects = Project.order(created_at: :desc).limit(10)

		@projects = Project.last_created_projects(10)
		if @projects.empty?
			render 'no_projects_found'
		end 
	end 
	def show
		unless @project = Project.find_by(id: params[:id])
		render 'no_projects_found'
		end
	end 
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
	def home
		 'home'
	end
	def contact
		 'contact'
	end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/entries/_form.html.erb
<% if @entry.errors.any? %>
	<ul>
		<% @entry.errors.full_messages.each do |error_msg| %>
		<li><%= error_msg %></li>
		<% end %>
	</ul>
<% end %>

<%= form_for [@project, @entry] do |f| %>
<%= f.label :hours %>
<%= f.text_field :hours, size: 4 %>
<br>
<%= f.label :minutes %>
<%= f.text_field :minutes, size: 4 %>
<br>
<%= f.label :date %>
<%= f.date_field :date, size: 4 %>
<br>
<%= f.label :comments %>
<%= f.text_field :comments, size: 4 %>
<br>
<%= f.submit 'Save' %>
<% end %>

<%= link_to("Cancel", projects_path) %>

app/views/entries/edit.html.erb
<%= render '/shared/form' %> 

app/views/entries/index.html.erb
<h1><%= @project.name %></h1>
<p>Total Hours Worked in this month: <%= @project.total_hours_in_month(@date.month, @date.year) %> hours </p>
<ul>
<% @project.entries.each do |entry| %>
<li>Entry ID: <%= entry.id %> - <%=entry.hours %> h <%= format("%.2d", entry.minutes) %> m- <%= entry.date.strftime("%Y-%m-%d") %> Comments: <%= entry.comments %> 
	<%= link_to("Edit", edit_project_entry_path(@project, entry)) %>
	<%= link_to('Delete', project_entry_path(@project,entry), method: :delete, data: {confirm:'Are you sure?'}) %>
</li>
<% end %>
</ul>

<% if flash[:notice] %>
	<%= flash[:notice] %>
<% end %>
<br>
<%= link_to("To the List", projects_path) %>
<br>
<%= link_to("New Entry", new_project_entry_path(@project)) %>

app/views/entries/new.html.erb
<% if flash[:error] %>
<%= flash[:error] %>
<% end %>
<h2> Creating a new entry in <%= @project.name %> project</h2>

<%= render '/shared/form' %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timetracking</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/index.html.erb
<ul>
	<% @projects.each do |project| %>
	<li><%= link_to(project.name, project_entries_path(project)) %>
		<% if project.description.present? %>
		- <%= project.description %>
		<% end %>
	</li>
	<% end %>
</ul>	

<%# @projects.each do |project| %>
<%# if project.description.present? %>
<%#=project.description %>
<%# end %>
<%# end %>

app/views/projects/no_projects_found.html.erb
<h1>PROJECT NOT FOUND!</h1>

app/views/projects/show.html.erb
<ul>
<li><%= @project.name %> : <%= @project.description %></li>
</ul>
<p><a href="/projects">Go Back to the list</a></p>

app/views/site/contact.html.erb
<h1>Contact</h1>
<p><a href="">contact@example.com</a></p>

app/views/site/home.html.erb
<h1>Welcome to the Time Tracking Tool!</h1>
<p>Ironhack powered</p>